version: "2"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=concourse
      - POSTGRES_USER=concourse
      - POSTGRES_PASSWORD=concourse
      - PGDATA=/database
  web:
    image: concourse/concourse
    environment:
      - CONCOURSE_BASIC_AUTH_USERNAME=concourse
      - CONCOURSE_BASIC_AUTH_PASSWORD=concourse
      - CONCOURSE_EXTERNAL_URL=http://localhost:8080
      - CONCOURSE_POSTGRES_DATA_SOURCE=postgres://concourse:concourse@postgres:5432/concourse?sslmode=disable
    links:
      - postgres
    volumes:
      - './keys/web:/concourse-keys'
    ports:
      - '8080:8080'
    command: web
  worker:
    image: concourse/concourse
    privileged: true
    environment:
      - CONCOURSE_TSA_HOST=web
      - CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8
    links:
      - web
    volumes:
      - './keys/worker:/concourse-keys'
    command: worker
