version: "2"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=concourse
  concourse:
    build: .
    ports:
      - '8080:8080'
      - '2222:2222'
    links:
      - postgres
    command: >
      web
      --basic-auth-username admin
      --basic-auth-password admin
      --session-signing-key /session_signing_key
      --tsa-host-key /host_key
      --tsa-authorized-keys /worker_key.pub
      --external-url http://localhost:8080
      --postgres-data-source postgres://postgres:postgres@postgres/concourse?sslmode=disable
    volumes:
      - './keys/session_signing_key:/session_signing_key'
      - './keys/host_key:/host_key'
      - './keys/worker_key.pub:/worker_key.pub'
  worker:
    build: .
    privileged: true
    links:
      - concourse
    command: >
      worker
      --work-dir /var/concourse/worker
      --tsa-host concourse
      --tsa-public-key host_key.pub
      --tsa-worker-private-key worker_key
      --garden-dns-server 8.8.8.8
      --garden-dns-server 8.8.4.4
    volumes:
      - './keys/host_key.pub:/host_key.pub'
      - './keys/worker_key:/worker_key'
