version: "2"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=concourse
  concourse:
    build: .
    ports:
      - '8080:8080'
      - '2222:2222'
    links:
      - postgres
    command: >
      web
      --basic-auth-username admin
      --basic-auth-password admin
      --session-signing-key /session_signing_key
      --tsa-host-key /host_key
      --tsa-authorized-keys /worker_key.pub
      --external-url http://localhost:8080
      --postgres-data-source postgres://postgres:postgres@postgres/concourse?sslmode=disable
    volumes:
      - './session_signing_key:/session_signing_key'
      - './host_key:/host_key'
      - './worker_key.pub:/worker_key.pub'
  worker:
    build: .
    privileged: true
    links:
      - concourse
    command: >
      worker
      --work-dir /var/concourse/worker
      --tsa-host concourse
      --tsa-public-key host_key.pub
      --tsa-worker-private-key worker_key
    volumes:
      - './host_key.pub:/host_key.pub'
      - './worker_key:/worker_key'
